FROM mustaevrr/python-38

RUN pip3 install tensorflow==2.5 && \
    pip3 install sklearn && \
    pip3 install matplotlib && \
    pip3 install numpy && \
    pip3 install pandas

WORKDIR "/app"

COPY . .

CMD ["python3", "src/main.py"]